### ISSUE TITLE
Spring Base64 return wrong result when using Basic authorization

### ISSUE THREAD

**Issue by toantd90** [virgo47/restful-spring-security#2]
This error occur when I put token to **Basic authorization** then loginPassword variable at line 100 of TokenAuthenticationFilter file return wrong result. I think it must be follow the format below "$username:$password". Can you check the filter by using **"Authorization: Basic $X_AUTH_TOKEN"**. I read your README.md file carefully, but I can find curl command for testing Basic Authorization. Thanks in advance for your help.

**Comment by virgo47** [comment]
Ok, the truth is, that `test.sh` does not test Basic authentication. However, I ran the application with `gradle bootRun` and when it was started, I initiated this command (with all the output shown):

```
$ curl -v -X POST -u admin:admin $URL
* Rebuilt URL to: http://localhost:8080/
* timeout on name lookup is not supported
*   Trying ::1...
* Connected to localhost (::1) port 8080 (#0)
* Server auth using Basic with user 'admin'
> POST / HTTP/1.1
> Host: localhost:8080
> Authorization: Basic YWRtaW46YWRtaW4=
> User-Agent: curl/7.45.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Fri, 18 Dec 2015 20:16:24 GMT
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< X-XSS-Protection: 1; mode=block
< X-Frame-Options: DENY
< X-Content-Type-Options: nosniff
< X-Auth-Token: RP5au9zTFR3VA1qfbu2hbfg1FOxh436m4CkLVGii5Hc=
< Content-Length: 0
< Server: Jetty(9.2.14.v20151106)
```

When you debug that `gradle bootRun` you can put breakpoint into `checkBasicAuthorization` method, and it definitely goes through tehre, `base64` var is filled with ``from the request and then the server log clearly shows output`loginPassword = admin:admin`.

As of now it qualifies as "cannot reproduce". In any case, please, read some guides how to report bugs, because there is virtually no chance someone understands it - and it's not because of bad English, but because little specifics in your report.
